/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FirebaseMessagingSwDotjsRouteImport } from './routes/firebase-messaging-sw[.]js'
import { Route as DataSafetyRouteImport } from './routes/data-safety'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GuidesSeasonalMaintenanceChecklistRouteImport } from './routes/guides.seasonal-maintenance-checklist'
import { Route as ApiScanInvoiceRouteImport } from './routes/api/scan-invoice'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AccountDeleteRouteImport } from './routes/account.delete'
import { Route as ApiPublicSendDueRemindersRouteImport } from './routes/api/public/send-due-reminders'
import { Route as ApiPublicRevenuecatWebhookRouteImport } from './routes/api/public/revenuecat-webhook'
import { Route as ApiPublicRevenuecatConfigRouteImport } from './routes/api/public/revenuecat-config'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicFirebaseConfigRouteImport } from './routes/api/public/firebase-config'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FirebaseMessagingSwDotjsRoute =
  FirebaseMessagingSwDotjsRouteImport.update({
    id: '/firebase-messaging-sw.js',
    path: '/firebase-messaging-sw.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const DataSafetyRoute = DataSafetyRouteImport.update({
  id: '/data-safety',
  path: '/data-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSeasonalMaintenanceChecklistRoute =
  GuidesSeasonalMaintenanceChecklistRouteImport.update({
    id: '/guides/seasonal-maintenance-checklist',
    path: '/guides/seasonal-maintenance-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScanInvoiceRoute = ApiScanInvoiceRouteImport.update({
  id: '/api/scan-invoice',
  path: '/api/scan-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDueRemindersRoute =
  ApiPublicSendDueRemindersRouteImport.update({
    id: '/api/public/send-due-reminders',
    path: '/api/public/send-due-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRevenuecatWebhookRoute =
  ApiPublicRevenuecatWebhookRouteImport.update({
    id: '/api/public/revenuecat-webhook',
    path: '/api/public/revenuecat-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRevenuecatConfigRoute =
  ApiPublicRevenuecatConfigRouteImport.update({
    id: '/api/public/revenuecat-config',
    path: '/api/public/revenuecat-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFirebaseConfigRoute = ApiPublicFirebaseConfigRouteImport.update({
  id: '/api/public/firebase-config',
  path: '/api/public/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-safety': typeof DataSafetyRoute
  '/firebase-messaging-sw.js': typeof FirebaseMessagingSwDotjsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/api/chat': typeof ApiChatRoute
  '/api/scan-invoice': typeof ApiScanInvoiceRoute
  '/guides/seasonal-maintenance-checklist': typeof GuidesSeasonalMaintenanceChecklistRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/revenuecat-config': typeof ApiPublicRevenuecatConfigRoute
  '/api/public/revenuecat-webhook': typeof ApiPublicRevenuecatWebhookRoute
  '/api/public/send-due-reminders': typeof ApiPublicSendDueRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-safety': typeof DataSafetyRoute
  '/firebase-messaging-sw.js': typeof FirebaseMessagingSwDotjsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/api/chat': typeof ApiChatRoute
  '/api/scan-invoice': typeof ApiScanInvoiceRoute
  '/guides/seasonal-maintenance-checklist': typeof GuidesSeasonalMaintenanceChecklistRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/revenuecat-config': typeof ApiPublicRevenuecatConfigRoute
  '/api/public/revenuecat-webhook': typeof ApiPublicRevenuecatWebhookRoute
  '/api/public/send-due-reminders': typeof ApiPublicSendDueRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-safety': typeof DataSafetyRoute
  '/firebase-messaging-sw.js': typeof FirebaseMessagingSwDotjsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/api/chat': typeof ApiChatRoute
  '/api/scan-invoice': typeof ApiScanInvoiceRoute
  '/guides/seasonal-maintenance-checklist': typeof GuidesSeasonalMaintenanceChecklistRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/revenuecat-config': typeof ApiPublicRevenuecatConfigRoute
  '/api/public/revenuecat-webhook': typeof ApiPublicRevenuecatWebhookRoute
  '/api/public/send-due-reminders': typeof ApiPublicSendDueRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-safety'
    | '/firebase-messaging-sw.js'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/account/delete'
    | '/api/chat'
    | '/api/scan-invoice'
    | '/guides/seasonal-maintenance-checklist'
    | '/invite/$token'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/api/public/revenuecat-config'
    | '/api/public/revenuecat-webhook'
    | '/api/public/send-due-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-safety'
    | '/firebase-messaging-sw.js'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/account/delete'
    | '/api/chat'
    | '/api/scan-invoice'
    | '/guides/seasonal-maintenance-checklist'
    | '/invite/$token'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/api/public/revenuecat-config'
    | '/api/public/revenuecat-webhook'
    | '/api/public/send-due-reminders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/data-safety'
    | '/firebase-messaging-sw.js'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/account/delete'
    | '/api/chat'
    | '/api/scan-invoice'
    | '/guides/seasonal-maintenance-checklist'
    | '/invite/$token'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/api/public/revenuecat-config'
    | '/api/public/revenuecat-webhook'
    | '/api/public/send-due-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DataSafetyRoute: typeof DataSafetyRoute
  FirebaseMessagingSwDotjsRoute: typeof FirebaseMessagingSwDotjsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiScanInvoiceRoute: typeof ApiScanInvoiceRoute
  GuidesSeasonalMaintenanceChecklistRoute: typeof GuidesSeasonalMaintenanceChecklistRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicFirebaseConfigRoute: typeof ApiPublicFirebaseConfigRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicRevenuecatConfigRoute: typeof ApiPublicRevenuecatConfigRoute
  ApiPublicRevenuecatWebhookRoute: typeof ApiPublicRevenuecatWebhookRoute
  ApiPublicSendDueRemindersRoute: typeof ApiPublicSendDueRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firebase-messaging-sw.js': {
      id: '/firebase-messaging-sw.js'
      path: '/firebase-messaging-sw.js'
      fullPath: '/firebase-messaging-sw.js'
      preLoaderRoute: typeof FirebaseMessagingSwDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-safety': {
      id: '/data-safety'
      path: '/data-safety'
      fullPath: '/data-safety'
      preLoaderRoute: typeof DataSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/seasonal-maintenance-checklist': {
      id: '/guides/seasonal-maintenance-checklist'
      path: '/guides/seasonal-maintenance-checklist'
      fullPath: '/guides/seasonal-maintenance-checklist'
      preLoaderRoute: typeof GuidesSeasonalMaintenanceChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-invoice': {
      id: '/api/scan-invoice'
      path: '/api/scan-invoice'
      fullPath: '/api/scan-invoice'
      preLoaderRoute: typeof ApiScanInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-due-reminders': {
      id: '/api/public/send-due-reminders'
      path: '/api/public/send-due-reminders'
      fullPath: '/api/public/send-due-reminders'
      preLoaderRoute: typeof ApiPublicSendDueRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/revenuecat-webhook': {
      id: '/api/public/revenuecat-webhook'
      path: '/api/public/revenuecat-webhook'
      fullPath: '/api/public/revenuecat-webhook'
      preLoaderRoute: typeof ApiPublicRevenuecatWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/revenuecat-config': {
      id: '/api/public/revenuecat-config'
      path: '/api/public/revenuecat-config'
      fullPath: '/api/public/revenuecat-config'
      preLoaderRoute: typeof ApiPublicRevenuecatConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firebase-config': {
      id: '/api/public/firebase-config'
      path: '/api/public/firebase-config'
      fullPath: '/api/public/firebase-config'
      preLoaderRoute: typeof ApiPublicFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DataSafetyRoute: DataSafetyRoute,
  FirebaseMessagingSwDotjsRoute: FirebaseMessagingSwDotjsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  ApiChatRoute: ApiChatRoute,
  ApiScanInvoiceRoute: ApiScanInvoiceRoute,
  GuidesSeasonalMaintenanceChecklistRoute:
    GuidesSeasonalMaintenanceChecklistRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicFirebaseConfigRoute: ApiPublicFirebaseConfigRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicRevenuecatConfigRoute: ApiPublicRevenuecatConfigRoute,
  ApiPublicRevenuecatWebhookRoute: ApiPublicRevenuecatWebhookRoute,
  ApiPublicSendDueRemindersRoute: ApiPublicSendDueRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
