/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FirebaseMessagingSwDotjsRouteImport } from './routes/firebase-messaging-sw[.]js'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiScanInvoiceRouteImport } from './routes/api/scan-invoice'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicSendDueRemindersRouteImport } from './routes/api/public/send-due-reminders'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicFirebaseConfigRouteImport } from './routes/api/public/firebase-config'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FirebaseMessagingSwDotjsRoute =
  FirebaseMessagingSwDotjsRouteImport.update({
    id: '/firebase-messaging-sw.js',
    path: '/firebase-messaging-sw.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanInvoiceRoute = ApiScanInvoiceRouteImport.update({
  id: '/api/scan-invoice',
  path: '/api/scan-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDueRemindersRoute =
  ApiPublicSendDueRemindersRouteImport.update({
    id: '/api/public/send-due-reminders',
    path: '/api/public/send-due-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFirebaseConfigRoute = ApiPublicFirebaseConfigRouteImport.update({
  id: '/api/public/firebase-config',
  path: '/api/public/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/firebase-messaging-sw.js': typeof FirebaseMessagingSwDotjsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/scan-invoice': typeof ApiScanInvoiceRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/send-due-reminders': typeof ApiPublicSendDueRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/firebase-messaging-sw.js': typeof FirebaseMessagingSwDotjsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/scan-invoice': typeof ApiScanInvoiceRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/send-due-reminders': typeof ApiPublicSendDueRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/firebase-messaging-sw.js': typeof FirebaseMessagingSwDotjsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/scan-invoice': typeof ApiScanInvoiceRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/send-due-reminders': typeof ApiPublicSendDueRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/firebase-messaging-sw.js'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/scan-invoice'
    | '/invite/$token'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/api/public/send-due-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/firebase-messaging-sw.js'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/scan-invoice'
    | '/invite/$token'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/api/public/send-due-reminders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/firebase-messaging-sw.js'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/scan-invoice'
    | '/invite/$token'
    | '/api/public/firebase-config'
    | '/api/public/razorpay-webhook'
    | '/api/public/send-due-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FirebaseMessagingSwDotjsRoute: typeof FirebaseMessagingSwDotjsRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiScanInvoiceRoute: typeof ApiScanInvoiceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicFirebaseConfigRoute: typeof ApiPublicFirebaseConfigRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicSendDueRemindersRoute: typeof ApiPublicSendDueRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firebase-messaging-sw.js': {
      id: '/firebase-messaging-sw.js'
      path: '/firebase-messaging-sw.js'
      fullPath: '/firebase-messaging-sw.js'
      preLoaderRoute: typeof FirebaseMessagingSwDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-invoice': {
      id: '/api/scan-invoice'
      path: '/api/scan-invoice'
      fullPath: '/api/scan-invoice'
      preLoaderRoute: typeof ApiScanInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-due-reminders': {
      id: '/api/public/send-due-reminders'
      path: '/api/public/send-due-reminders'
      fullPath: '/api/public/send-due-reminders'
      preLoaderRoute: typeof ApiPublicSendDueRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firebase-config': {
      id: '/api/public/firebase-config'
      path: '/api/public/firebase-config'
      fullPath: '/api/public/firebase-config'
      preLoaderRoute: typeof ApiPublicFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FirebaseMessagingSwDotjsRoute: FirebaseMessagingSwDotjsRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiScanInvoiceRoute: ApiScanInvoiceRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicFirebaseConfigRoute: ApiPublicFirebaseConfigRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicSendDueRemindersRoute: ApiPublicSendDueRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
